---
title: 'History Girls By: Adele Geras'
author: Molly Vonk
date: '2017-10-03'
slug: history-girls-by-adele-geras
categories:
  - Series
tags:
  - Historical Fiction
---

credited to https://www.goodreads.com/author/show/221019.Ad_le_Geras

## Synopsis

Adele Geras has written two historical fiction novellas under the series called History Girls, Troy and Ithaka. Each book is a retelling of a historical event from Greek history as if the Greek Gods were very much real, as the meddle in the lives of mortals. With vitality and grace, Adele Geras breathes personality, heartbreak and humor into this classic story, told through the eyes of the women of Troy and Ithaka.

## The Books

#### Troy

The Siege of Troy has lasted almost ten years. Inside the walled city food is (Malacca). and death is common. From the heights of Mount Olympus The Gods keep watch. But Aphrodite. Goddess of Love. is bored with the endless. dreary war. Aided by Eros's bow. the goddess sends two sisters down a bloody path to an awful truth: In the fury of war. love strikes the deadliest blows. Heralded by fans and critics alike. Adle Geras eathes personality. hearteak. and humor into this classic story. Told from the point of view of the women of Troy. portrays the last weeks of the Trojan War. when women are sick of tending the wounded. men are tired of fighting. and bored gods and goddesses find ways to stir things up. 

#### Ithaka

Many years have passed since the end of the Trojan War, and Penelope is still waiting for her husband, Odysseus, to return home. The city of Ithaka is overrun with uncouth suitors from the surrounding islands who are vying to win Penelope's hand in marriage, thereby gaining control of the land. When a naked, half-drowned man washes up on the beach, everything changes. . . .

Told through the eyes of Klymene, a young girl who is like a daughter to Penelope--and who longs for more than friendship from the young prince Telemachus--Ithaka captures the quiet strength and patience of a woman's enduring love for her husband and the ensuing chaos that threatens all as Penelope is pressured to remarry.