---
title: 'Fahrenheit 451 By: Ray Bradbury'
author: Molly Vonk
date: '2017-10-09'
slug: fahrenheit-451-by-ray-bradbury
categories:
  - Novel
tags:
  - Classic
  - Dystopia
  - Science Fiction
---

Credited to https://www.goodreads.com/book/show/4381.Fahrenheit_451

## Synopsis

Guy Montag is a fireman. His job is to burn books, which are forbidden, being the source of all discord and unhappiness. Even so, Montag is unhappy; there is discord in his marriage. Are books hidden in his house? The Mechanical Hound of the Fire Department, armed with a lethal hypodermic, escorted by helicopters, is ready to track down those dissidents who defy society to preserve and read books.


Fahrenheit 451 is a masterwork of twentieth-century literature. The classic dystopian novel of a post-literate future, Fahrenheit 451 stands alongside Orwell's 1984 and Huxley's Brave New World as a prophetic account of Western civilization's enslavement by the media, drugs and conformity. Bradbury's powerful and poetic prose combines with uncanny insight into the potential of technology to create a novel which, decades on from first publication, still has the power to dazzle and shock.